# Generated by Django 6.0.6 on 2026-06-10 10:25

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabbycatInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(help_text='Root URL of the Tabbycat site, e.g. https://sda.calicotab.com')),
                ('api_token', core.fields.EncryptedTextField(help_text='A staff API token with permission to view private URLs and contacts.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Tabbycat instance',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_running', models.BooleanField(default=False, help_text='A round is currently in progress.')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.tabbycatinstance')),
            ],
            options={
                'ordering': ['-is_running', 'seq', 'name'],
                'unique_together': {('instance', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PrivateURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', core.fields.EncryptedTextField()),
                ('source_email', models.EmailField(help_text='The Tabbycat adjudicator email this URL was matched on.', max_length=254)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_urls', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_urls', to='core.tournament')),
            ],
            options={
                'unique_together': {('user', 'tournament')},
            },
        ),
    ]
