# Generated by Django 6.0.6 on 2026-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateurl',
            name='self_added',
            field=models.BooleanField(default=False, help_text='Added by the user from a private URL/QR rather than matched by sync.'),
        ),
        migrations.AlterField(
            model_name='privateurl',
            name='source_email',
            field=models.EmailField(blank=True, help_text='The Tabbycat adjudicator email this URL was matched on (blank if self-added).', max_length=254),
        ),
    ]
