# Generated by Django 6.0.6 on 2026-06-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_privateurl_self_added_alter_privateurl_source_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_visible', models.BooleanField(default=True, help_text='When unchecked, the privacy policy page is hidden (returns 404) and its link disappears from the footer.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
