# Generated by Django 6.0.6 on 2026-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_html_en',
            field=models.TextField(blank=True, default='', help_text='Content shown on the privacy page in English. HTML is allowed. Falls back to the Slovak text when left blank.', verbose_name='Privacy policy — English (HTML)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_html_sk',
            field=models.TextField(blank=True, default='', help_text='Content shown on the privacy page in Slovak. HTML is allowed (e.g. <h2>, <p>, <ul>, <a>). Leave blank for an empty page.', verbose_name='Privacy policy — Slovak (HTML)'),
        ),
    ]
